### ISSUE TITLE
Bug - problems with css in versions 8 and 9 of internet explorer - Portão padrão plone do Governo federal

### ISSUE THREAD

**Issue by Andrsen** [plonegovbr/brasil.gov.temas#107]
Good night, 
I'm an employee of the Ministry of Justice of Brazil, we use our website in Plone: www.justica.gov.br/portaopadrao, occurs that is having problems with css in versions 8 and 9 of internet explorer. Could anyone help? Looks like it is giving error in the script that generates the css on line 21.
Almerindo Trindade

Version
◾Plone 4.3.2 (4307)
◾CMF 2.2.7
◾Zope 2.13.21
◾Python 2.7.5+ (default, Sep 19 2013, 13:48:49) [GCC 4.8.1]
◾PIL 1.7.8 (Pillow)

**Comment by idgserpro** [comment]
Testei a versão mais nova do IDG (1.0.5) no IE 8 e 9 e esses erros não ocorrem mais. @Andrsen você pode testar para podermos fechar esse relato?

**Comment by idgserpro** [comment]
@hvelarde seria o caso de fecharmos o relato por não haver resposta, ainda mais que o suporte a esses navegadores pela própria Microsoft [terminou em 12 de janeiro de 2016](https://www.microsoft.com/pt-br/WindowsForBusiness/End-of-IE-support)?
