### ISSUE TITLE
Adição da imagem estática "Brasil, pátria educadora" no tema.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#109]
O pacote atual brasil.gov.temas tem a imagem antiga no rodapé, e a barra atual tem um rodapé dinâmico, que "sobrescreveria" essa imagem do rodapé em tempo real via javascript. 

Acontece que a barra não sendo carregada corretamente por causa do problema dos certificados https (os certificados do ministério do planejamento não vem por padrão nos navegadores) ela não sobrescreve a imagem ficando portanto a antiga. 

Soluções:
- Ou se resolve o problema do certificado, algo além de nosso escopo de desenvolvimento;
- O usuário final aceita manualmente o certificado como proposto em http://barra.governoeletronico.gov.br/atualize.html para que o rodapé dinâmico funcione a partir da segunda visita (a primeira vez sempre vai dar problema);
- Paliativamente deve-se alterar a imagem do rodapé presente brasil.gov.temas com a nova logo "Brasil, pátria educadora". Essa segunda opção foge um pouco do conceito de rodapé dinâmico mas tem o mesmo retorno visual e também é a forma mais simples de resolver esse problema do certificado (pois está ao nosso alcance de resolver). Seria interessante colocar a condição de renderização dessa imagem como um parâmetro/flag no painel de controle pois, na época de eleição, haveria a opção de desabilitá-la pelo gestor de conteúdo (ou seja, Site Administrator e não apenas o Manager), não sendo necessária solicitação de alteração de html ou de release. Dessa forma, resolve-se o problema atual do rodapé e em época de eleição não se é demandado alteração de html em todos os portais

Esse relato complementa o https://github.com/plonegovbr/brasil.gov.barra/issues/12. Seria interessante que as duas correções saiam num mesmo release.

**Comment by caduvieira** [comment]
@idgserpro O certificado não é do ministério do planejamento. A cadeia de certificados parte do ITI/ICP-Brasil e inclusive o certificado utilizado pelo barra.brasil.gov.br é do SERPRO. E de acordo com o bug no Mozilla é de responsabilidade dos CAs abaixo do ITI pedir a inclusão dos certificados. Nesse caso deve ser o SERPRO a pedir isso. [1] Então isso está no escopo do SERPRO pelo menos para o caso do Mozilla.

O que não impede a alteração no rodapé para "Brasil, pátria educadora". Mas para ficar mais perene eu retiraria completamente a logo e deixaria somente a do 'Acesso a Informação'

![certificado barra.brasil SERPRO](https://cloud.githubusercontent.com/assets/3831408/6715678/c879ccb4-cd7e-11e4-84aa-66701f9ffba5.png)

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=438825#c126

**Comment by idgserpro** [comment]
Quando disse além de nosso escopo quis dizer no escopo de desenvolvimento pois envolve infra-estrutura. Editei a mensagem pra ficar mais claro.

Apesar disso a análise ainda persiste: a cadeia de certificados não instalada.

Sobre a imagem, voto por colocar a imagem no rodapé como o proposto uma vez que a mesma só é modificada em períodos de eleição (portanto, por mais que conceitualmente essa não seja a melhor solução é a que tem melhor custo benefício).

Remover a imagem vai apenas mudar o questionamento de usuários de "está aparecendo a imagem errada" para "não está aparecendo nenhuma imagem no rodapé".

**Comment by caduvieira** [comment]
Prefiro retirar a imagem pois se tiver e a barra falhar pelo certificado vai ficar aparecendo a imagem. E, por lei, isso não pode acontecer em determinados períodos.

**Comment by idgserpro** [comment]
A idéia da imagem aparecer quando o certificado falhar é exatamente essa, ser um fallback enquando esse problema do certificado não é resolvido pois certificação está além de nossa capacidade de desenvolvimento no plonegovbr.

Esses períodos onde as imagens tem de ser removidos geralmente são bem espaçados, e os órgãos são sempre avisados e demandam a alteração. Isso já é internalizado.

Veja, conceitualmente, você está certo, a nossa proposta é sermos *pragmáticos* pra um problema real atual que está impactando todo portal de governo que tenha esse problema de certificado ao invés do problema que ocorre apenas em eleições, ainda mais que os gestores já estão cientes e acostumados na solicitação de remoção.

**Comment by caduvieira** [comment]
Sendo pragmático: O Ministério do Planejamento solicitou para isso ser feito e foi cobrado cerca de 1000,00 por sítio. Então uma retirada de HTML em 50 sítios custa para o governo 50.000,00 e para todos os Ministérios (39) mais as autarquias [1] vai custar mais de 4 milhões de reais.

Ainda acho que a solução seja o SERPRO e as outras entidades certificadores entrarem com pedido para o certificado na mozilla [2] e com os outros. O SERASA entrou com esse pedido mas não continuou [3]. O SERPRO pode agir nesse sentido. 

O plonegovbr pode melhorar o gasto público do dinheiro.

[1] http://pt.wikipedia.org/wiki/Lista_de_autarquias_federais_do_Brasil
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=438825#c138
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=457921

**Comment by idgserpro** [comment]
Esse problema de certificado está além do escopo do plonegovbr, nesse pacote em específico. De qualquer forma, essa discussão do certificado tentará ser levada aos responsáveis para ver o que pode ser feito para agilizar esse processo.

Só que enquanto isso não é resolvido, o rodapé não mostra a imagem corretamente e aí todos os portais terão de ter o tema customizado via zmi para ter a imagem correta o que inviabilizaria atualização automática de ambientes para cada novo release, o que também não seria o ideal numa visão de eficiência.

Novamente, como eu disse, o correto é consertar o certificado, mas se não fizermos esse paliativo, *ainda* precisamos ficar customizando html de qualquer forma. E pior: para todo novo release do brasil.gov.portal, mesmo que não esteja em época de eleição.

Foi nesse sentido que foi levantada a bola de ser "pragmático", o problema já está aí e não há como resolver o problema do certificado a curto prazo, e isso vai gerar trabalhos manuais de customização em todos os portais, para *todo novo release*.

Após essa discussão, acho que nesse cenário o mais sensato é um outro meio termo: coloca-se a condição de renderização dessa imagem como um parâmetro no painel de controle e, na época de eleição, opção de desabilitá-la pelo gestor de conteúdo, não sendo necessária solicitação de alteração de html ou de release. Dessa forma, resolve-se o problema atual do rodapé e em época de eleição não se é demandado alteração de html em todos os portais, será apenas uma alteração pontual no brasil.gov.barra. A barra em javascript do Ministério do Planejamento não sofre alteração.

Qual sua opinião sobre essa outra abordagem?

**Comment by hvelarde** [comment]
:+1:

**Comment by caduvieira** [comment]
:+1:

**Comment by idgserpro** [comment]
Prezados,

Já que houve um consenso com relação a

```
coloca-se a condição de renderização dessa imagem como um parâmetro no painel de controle
```

Qual deveria ser o padrão? Por padrão, não mostramos a imagem? Eu voto por essa abordagem por seguir a mesma lógica hoje do brasil.gov.barra, que tem a opção "mostrar barra local". Inclusive, voto pela mesma nomenclatura, ou seja, "usar imagem local do rodapé". Quais são suas opiniões?

**Comment by idgserpro** [comment]
@caduvieira já que votamos por manter a imagem, acho que no [seu pull request de acessibilidade](https://github.com/plonegovbr/brasil.gov.temas/pull/116) por enquanto ela pode ser readicionada.

**Comment by idgserpro** [comment]
Corrigido em:

https://github.com/plonegovbr/brasil.gov.temas/commit/ffa35e8bd17988e9c898499933d81ebd5f6e097f

Estou fechando esse relato e abri:

https://github.com/plonegovbr/brasil.gov.barra/issues/24

para discutir a configuração para mostrar ou não a imagem.
