### ISSUE TITLE
Com a adição da ul de linguas, o usuário logado recebe um item "Configuração do Site" no cabeçalho quebrando o layout

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#112]
Logado:

![Logado](https://cloud.githubusercontent.com/assets/8203476/7167018/1d5dac40-e388-11e4-8ba1-6088744f265e.png)

Não logado:

![Não logado](https://cloud.githubusercontent.com/assets/8203476/7167026/2ce12d9a-e388-11e4-8050-2a71abfe9ae9.png)

Vejo as seguintes opções de soluções:
- Corrigir o css (parece ser complicado, pois é a largura do site que faz a div das actions de sitemap não encaixarem);
- Diminuir a fonte e o espaçamento entre os itens das actions de acessibilidade, sitemap e etc (possivelmente fugiria do guia de estilos do IDG);
- Esconder a listagem de línguas se o usuário estiver logado;
- Remover o item "Configuração do site", mesmo porque ele não está previsto nas [diretrizes (página 19)](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/diretrizes-comunicacao-digital-governo-federa-jan2014.pdf) e nem no [guia de estilo (página 42)](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/guia-de-estilo-identidade-padrao-comunicacao-digital-fev2015.pdf) do IDG da SECOM. Isso deveria ser feito como um upgradeStep em brasil.gov.portal, setando a action de "Configuração do Site" como invisível.

Quais são suas opiniões?

**Comment by caduvieira** [comment]
Sugiro retirar o item Configurações do Site para ficar conforme diretrizes do IDG da SECOM.

**Comment by hvelarde** [comment]
@caduvieira e depois como você vai acessar esse recurso?

**Comment by caduvieira** [comment]
No menu do admin depois de logado.
![image](https://cloud.githubusercontent.com/assets/3831408/7635796/822ee7c0-fa39-11e4-95a7-b5e945d6de8d.png)

**Comment by idgserpro** [comment]
O problema que vemos nessa modificação é remover uma funcionalidade que vários clientes já estão habituados. Com a atualização, vão chover reclamações "sumiu o item de menu", etc. Por isso colocamos aqui para discussão. A possibilidade de remover as actions de línguas só quando um usuário estiver logado também meio que só muda a reclamação de "não estou vendo o configuração" para "não estou vendo o link de línguas" (apesar disso, o clique do usuário nesse link não teria a mesma frequência que o de configuração, ou seja, impacto seria minimizado). Teria de ser muito bem documentado.

@caduvieira, consegue ver alguma solução pra solucionar o problema do css com respeito à largura do site? Se não tivermos uma solução, teremos de uma forma ou de outra acabar removendo mesmo esse link.

**Comment by winstonf88** [comment]
O item deve ser removido no produto do [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal).
Criei uma nova issue para isso https://github.com/plonegovbr/brasil.gov.portal/issues/212.
