### ISSUE TITLE
Css de línguas não mantém cores da identidade visual previstas nas diretrizes

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#114]
Ao ativar a `ul#language` para um site multilíngue, alguns temas estão com cores incorretas na identidade visual.

**Temas corretos:**

![selecao_047](https://cloud.githubusercontent.com/assets/8203476/7211359/782b5e70-e530-11e4-8658-0bfcfc9ebc26.png)

![selecao_049](https://cloud.githubusercontent.com/assets/8203476/7211363/7fcf6612-e530-11e4-95ef-700ea0685009.png)

**Temas incorretos:**

![selecao_048](https://cloud.githubusercontent.com/assets/8203476/7211362/7cbed656-e530-11e4-967d-dc38d552c217.png)

![selecao_050](https://cloud.githubusercontent.com/assets/8203476/7211365/84ea621e-e530-11e4-9d16-3e0a2331f7e1.png)

**Comment by winstonf88** [comment]
@idgserpro Poderia me informar como ativar esta barra de línguas para eu corrigir o problema?

**Comment by idgserpro** [comment]
@winstonf88, basta seguir como presente na documentação em https://github.com/plonegovbr/brasil.gov.temas#links-de-linguas-no-topo-internacionalizacao.

**Comment by winstonf88** [comment]
@idgserpro Obrigado. 
Apenas como sugestão, não seria mais fácil/melhor adicionar esses 2 itens no site_actions e apenas deixalos desabilidatos?

**Comment by idgserpro** [comment]
Se fosse só o caso de mudar o checkbox pra visível ou não, eu acho que seria interessante sim essa modificação de adição das actions de uma vez em brasil.gov.portal. Mas como existem dados muito específicos de cada portal [(como a url do portal traduzido)](https://github.com/plonegovbr/brasil.gov.temas/blob/master/src/brasil/gov/temas/themes/amarelo/rules.xml#L76), achamos melhor a adição dessa action só quando há demanda ao invés de ter uma action invisível "incompleta" esperando essa url.

Isso pode ser discutido, mas no momento preferimos como está. @hvelarde Opiniões?

**Comment by winstonf88** [comment]
Entendido.

**Comment by hvelarde** [comment]
acho que podemos abrir uma issue para discussão e anunciar na lista.

**Comment by idgserpro** [comment]
Eu voto pra deixar como está pelos motivos citados. @winstonf88, caso queira levar adiante, pode postar na lista como sugerido pelo @hvelarde para pegarmos outros pontos de vista e dependendo do que for discutido poderemos dar outro parecer. Obrigado!
