### ISSUE TITLE
Pinar collective.cover

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#118]
O collective.cover não está pinado. É necessário pinar para versão 1.0a9, porque a versão mais nova está com problema. Ver: https://github.com/plonegovbr/brasil.gov.tiles/issues/130

**Comment by idgserpro** [comment]
Resolvido em: https://github.com/plonegovbr/brasil.gov.temas/commit/b8adfccfb0ba39136f103110348dcbac42afb9e5

**Comment by hvelarde** [comment]
@idgserpro liberamos a versão 1.0a11 ha pouco; gostaria atualizar até essa versão que é a melhor e mais estável já disponibilizada.

podem ajudar a testar isso ai?

**Comment by idgserpro** [comment]
Sim. Quando tive um tempo testo isso.
