### ISSUE TITLE
Atender item 4.2 - Primeira folha de contraste do e-MAG 3.1 - links em alto-contraste em amarelo e sublinhados

### ISSUE THREAD

**Issue by tomfsa** [plonegovbr/brasil.gov.temas#119]
Prezados, recebemos um relatório de auditoria recomendando ações para atendimento ao item 4.2 - Primeira folha de contraste - informando que os links em alto-contraste devem ser apresentados em amarelo e sublinhados.

**Comment by caduvieira** [comment]
A maioria disso está no css do brasil.gov.portal.
https://github.com/plonegovbr/brasil.gov.portal/pull/201

**Comment by idgserpro** [comment]
@caduvieira podemos fechar esse ou ainda tem que fazer algo?

**Comment by caduvieira** [comment]
Não encontrei nada mais a fazer. Pode fechar.

Em 29 de julho de 2015 11:21, idgserpro <notifications@github.com> escreveu:

**Comment by idgserpro** [comment]
Obrigado @caduvieira!
