### ISSUE TITLE
Links em alto-contraste devem ser apresentados em amarelo e sublinhados

### ISSUE THREAD

**Issue by winstonf88** [plonegovbr/brasil.gov.temas#124]
Segundo o Serpro foi recomendando ações para atendimento ao item 4.2 - Primeira folha de contraste - informando que os links em alto-contraste devem ser apresentados em amarelo e sublinhados.

**Comment by idgserpro** [comment]
Corrigido em: https://github.com/plonegovbr/brasil.gov.temas/issues/119
