### ISSUE TITLE
Erro na aparência do portal após o login

### ISSUE THREAD

**Issue by luizgsbraz** [plonegovbr/brasil.gov.temas#131]
Logo após o login, a tela "Você agora está autenticado" fica prejudicada, conforme mostra a figura.

![login_bug](https://cloud.githubusercontent.com/assets/7255936/18969231/acaf25ee-8662-11e6-8130-4c2ca93ebc4d.png)

Quando clico sobre o nome do Portal a aparência do site volta ao normal.

**Comment by idgserpro** [comment]
Um discussão sobre isso pode ser vista em:

https://colab.interlegis.leg.br/archives/thread/plonegov-br/tela-de-login

**Comment by hvelarde** [comment]
esse é um velho problema; tal vez o @agnogueira lembra como consertar.

**Comment by claytonc** [comment]
Hector,

A mesma solução que publiquei em 2014 [1] utilizei no portal idg.

[1]
https://colab.interlegis.leg.br/archives/thread/plonegov-br/tela-de-login#msg-148493

--

Clayton

Em 29 de setembro de 2016 19:36, Héctor Velarde <notifications@github.com>
escreveu:

**Comment by luizgsbraz** [comment]
@claytonc, se bem entendi foi isso que você fez. Aqui resolveu o problema reportado. Mas não sei se gerou outros.

**Comment by luizgsbraz** [comment]
O iniciante baixa o IDG, segue o tutorial, faz o primeiro login e kabum! Não seria o caso de distribuir o tema já com essa mínima modificação? @agnogueira @hvelarde

**Comment by luizgsbraz** [comment]
Aqui, quando demandado, o fornecedor criou um pacote (pf.portal.policy) com um template que sobrescreve o Plone, comentando este trecho ai:

https://github.com/luizgsbraz/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_login/login_form.cpt#L84-L89 

Essa solução exige que o usuário, no mínimo, crie um pacote se quiser não conviver com o problema. E se não quiser fazer a modificação direto no Plone.

**Comment by hvelarde** [comment]
@luizgsbraz eu estou esperando desde o 19 de novembro de 2014 pelo patch que corrigia isso e que ia ser "disponibilizado pra comunidade" ;-)

**Comment by agnogueira** [comment]
Uma pena que tanta gente tenha corrigido o problema mas ninguém tenha corrigido da maneira correta e que ajudaria todo mundo, que é corrigindo no pacote original. @luizgsbraz sempre exija dos seus fornecedores que as correções sejam feitas no código original, senão o problema sempre volta te assombrar no futuro.

**Comment by idgserpro** [comment]
> @luizgsbraz sempre exija dos seus fornecedores que as correções sejam feitas no código original

É muito importante uma sensibilização com fornecedor/cliente no que diz respeito ao ciclo de vida da solução toda vez que uma customização entra em jogo. Mas muitas vezes, o cliente/fornecedor não tem sequer noção de todo esse conceito de ciclo de vida, de release, portanto, considero essencial essa sensibilização de nossa parte já que conhecemos todo o processo.

Existem dois pontos principais nessa discussão ao meu ver que geralmente nós levantamos para os clientes:

1 - O lado do "bom senso" do funcionamento em comunidade e a responsabilidade de cada um
==========================

Coloquei entre aspas por ser uma questão meio subjetiva, pois diz respeito a colocar uma correção que beneficiaria todo mundo, principalmente por ser um pacote utilizado por governos e instituições federais (poderíamos inclusive pensar no princípio da eficiência da administração pública), mas *não necessariamente* traz algum benefício **direto** pra quem está customizando.

2 - O lado prático e pragmático que envolve custo a longo prazo de manter a customização
==========================

Se o cliente não liga para o item acima (e está no seu direito), é importante indicar para o mesmo que **toda customização** que você adiciona no seu policy que não vem pra comunidade é um ponto de verificação de análise de impacto para **toda nova versão que você atualizar** do IDG. É um passo manual, custoso e com grande chance de erros: geralmente quando a customização é feita não segue o mesmo cuidado com testes e integração que a comunidade segue e, supondo que segue, você então agora precisa criar uma infra estrutura interna para gestão desse código, integração contínua e etc quando temos isso hoje pronto no github.

Num primeiro momento, é tentador colocar direto no policy: é mais rápido e fácil, não tem discussão na comunidade, não tem de esperar release, você instala no cliente no mesmo dia... mas imagine fazer a mesma coisa em 10 portais, criar um ciclo de vida paralelo de instalar o IDG, depois a sua customização... fazer o desenvolvimento voltado pra comunidade é sim mais custoso no *curto* prazo mas depois são só ganhos.

Apesar disso, sabemos que o mundo não é perfeito: há modificações que tem de ser aplicadas pelos mais diversos motivos e ensejos do nosso cliente, falta de recursos (tanto humanos quanto verbas), só recomendamos que, mesmo tendo essas customizações pontuais para "apagar incêndio", que depois se tente que elas sejam replicadas na comunidade. Isso já aconteceu com a gente e garanto que aconteceu com todos vocês uma vez ou outra.

Isto posto, @luizgsbraz, não sabemos a abertura que você possui no seu órgão para tentar pleitear "consertar isso do jeito correto" pois sabemos que cada órgão tem os seus recursos, mas seria interessante se você pudesse ver isso. E aproveito para perguntar ao @agnogueira: qual pra você seria o jeito "correto" de corrigir isso? Customizamos o login_form no projeto IDG usando z3c.jbot? @hvelarde, @rodfersou e @claytonc qual a opinião de vocês?

**Comment by agnogueira** [comment]
@idgserpro Muito bom seus comentários. Concordo com você, em alguns casos falta vontade, em outros conhecimento. Podemos trabalhar na parte do conhecimento, e temos falhado muito nisso. Faz tempo que não realizamos palestras, encontros, eventos. Precisamos voltar a realiza-los e ajudar no que for possível cada interessado.

Com relação ao "jeito correto", não quis entrar no mérito da solução. Na minha mensagem o jeito correto é o compartilhado, de maneira a atingir o maior número de usuários possíveis.

Se o problema é do core do Plone, corrigimos no core do Plone
Se o problema é num complemento, corrigimos no complemento
Se o problema é no IDG, corrigimos no IDG
Se o problema é na minha customização, corrigo localmente

Sempre nessa ordem.

Agora com relação ao jeito certo, tecnicamente falando, deixo com vocês que conhecem bem mais do que eu.

**Comment by claytonc** [comment]
@idgserpro Também achei muito bom o seus comentários. 

@idgserpro eu só acho um pouco burocrático na aceitação de algumas submissões exemplo [1] que solicitou fazer um teste no robot framework, eu só adicionei uma classe css.

@agnogueira eu tento seguir a mesma ordem na correção de problemas, mas nem sempre isso funciona e tenho que adicionar as correções do IDG na minha customização. 

Realmente faz tempo que não realizamos palestras, encontros, eventos.

Com relação a customização do login_form eu sempre coloquei no skins de algum produto nunca utilizei o z3c.jbot no login_form.


[1] https://github.com/plonegovbr/brasil.gov.tiles/pull/151

**Comment by luizgsbraz** [comment]
Prezados,

antes de tudo, obrigado pelas contribuições. Concordo com todos.
Quem me conhece sabe o quanto prezo o retorno das melhorias para a comunidade.

Não tinha meios para exigir do fornecedor o retorno da melhoria à comunidade.

Não fiz, pessoalmente, porque não sabia como. Na verdade, continuo sem saber. :-)

No entanto, agora que não tenho mais fornecedor (o contrato não foi prorrogado!) estou aprendendo e tentando fazer eu mesmo.  

Acabei de fazer um pull request.

**Comment by idgserpro** [comment]
> Não fiz, pessoalmente, porque não sabia como. Na verdade, continuo sem saber. :-p

Sim, esse início costuma ser complicado. Nossa idéia é depois viabilizar o uso de https://github.com/blog/2111-issue-and-pull-request-templates para que, ao fazer um pull request, um mínimo de direcionamento seja dado.

**Comment by idgserpro** [comment]
>  eu só acho um pouco burocrático na aceitação de algumas submissões exemplo [1] que solicitou fazer um teste no robot framework, eu só adicionei uma classe css.

@claytonc É sempre aquela discussão: será que o *overhead* de adicionar esse teste vale a pena pelo benefício que ele traz? Estamos sempre abertos para esse questionamento porque nós mesmos volta e meia questionamos.

A título de exemplo, veja [esse pull request](https://github.com/plonegovbr/brasil.gov.portal/pull/316/files): o teste é **maior** do que a implementação, mas achamos o teste importante porque esse é um problema que quebra a capa do site e portanto vale a pena esse cuidado pois pode impactar todos os portais IDG hoje em produção.

No caso do pull request (PR) [que você mencionou](https://github.com/plonegovbr/brasil.gov.tiles/pull/151), você pode complementá-lo e questionar "por que preciso de um robots aqui? Acho desnecessário por tal e tal motivo" para que se discuta. Entenda que inicialmente temos todo esse cuidado porque temos que ter sempre em mente que qualquer modificação pode impactar toda instalação que hoje utiliza o IDG: temos que lembrar que há instalações que começaram na 1.1.4, instalações que começaram na 1.0.5, e todas não podem quebrar com uma alteração que é feita no pacote. É uma responsabilidade muito grande.

Reconhecemos que podemos melhorar esse processo de direcionamento para quem nunca contribuiu e nossa idéia no futuro é fazer uso de https://github.com/blog/2111-issue-and-pull-request-templates.

**Comment by claytonc** [comment]
@idgserpro 

Sobre os testes eu acho na minha opinião dependendo das alterações tipo como a que mencionei que são visuais primeiro a correção e testar em todos os navegadores e depois se for realmente importante criar um teste automatizado com robot framework.

Agora eu concordo se é para ter testes deveria ter teste em todos os tiles com robot framework, acho que teria detectado a quebra nos tiles de banner rotativo e carrossel nas versões do idg 1.1.3 e 1.1.4, pois na versão 1.0.5 não ocorria o problema.

Mas também acho que poderia ter algum evento ou reunião para tratar de assuntos técnicos convidando os desenvolvedores e infraestrutura dos órgão que utiliza o IDG, até para expor as dificuldades, dúvidas, troca de experiência etc

**Comment by luizgsbraz** [comment]
Sobre TDD, tentei usar o robot mas ele andou estranhando o firefox-esr.

![erro no robot](https://cloud.githubusercontent.com/assets/7255936/19125338/1a5c8cb8-8b0d-11e6-9aad-ba3c8003f487.png)

Quem sabe no próximo pull request eu acrescente uns testes...

**Comment by idgserpro** [comment]
@luizgsbraz esse Test Criacao Site é do ```brasil.gov.portal```. Veja que ele está funcionando no master:

https://travis-ci.org/plonegovbr/brasil.gov.portal/jobs/164649029

Você está utilizando o master?
