### ISSUE TITLE
Deveríamos adicionar "Imprimir" e "Reportar Erro" hoje presente em brasil.gov.agenda em brasil.gov.portal?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#137]
[Nessa implementação](https://github.com/plonegovbr/brasil.gov.agenda/blob/3e18d62cb9b76ac7dc009c1a805ebfceefe439be/src/brasil/gov/agenda/browser/templates/agendaview.pt#L49), temos os botões de "Imprimir" e "Reportar Erro" no brasil.gov.agenda:

![selecao_012](https://cloud.githubusercontent.com/assets/8203476/22215573/00f5272c-e183-11e6-849e-36664987c68a.png)

Seria o caso de adicionarmos também em brasil.gov.portal? Deveria ser um behavior, uma viewlet? Em quais tipos deveriam aparecer?

cc @agnogueira @hvelarde @rodfersou

**Comment by rodfersou** [comment]
@idgserpro para que serve o botão **Reportar erro**?

O botão **Imprimir** era algo muito comum nos anos 90, mas atualmente é tratado como uma prática ruim para sites web além de ser desnecessário, se alguém quiser imprimir, pode utilizar o botão imprimir do navegador.

Em nossos clientes, costumamos fazer um serviço de conscientização de que uma página web não funciona dessa forma, por que podemos mudar para diversos aparelhos diferentes (user agents) e o aparelho que vai dizer se é possível ou não realizar uma impressão dependendo do contexto.

**Comment by idgserpro** [comment]
> O botão Imprimir era algo muito comum nos anos 90, mas atualmente é tratado como uma prática ruim para sites web além de ser desnecessário, se alguém quiser imprimir, pode utilizar o botão imprimir do navegador.

Ok. Então devemos remover ele do brasil.gov.agenda? Eu defendo a consistência na interface. Ou se adiciona o que está no Agenda nos demais, ou removemos do Agenda.

> para que serve o botão Reportar erro?

Essa é uma função não documentada em que você pode registrar um formulário de id "relatar-erros" que o pacote [gera um link pra você](https://github.com/plonegovbr/brasil.gov.agenda/blob/1ca46470ac21fa920a9c8cb54a84991861d92208/src/brasil/gov/agenda/browser/agenda.py#L75) desse formulário para que o usuário possa reportar erros encontrados no portal. Inclusive [há relatos para melhorar essa renderização](https://github.com/plonegovbr/brasil.gov.agenda/issues/62).

**Comment by hvelarde** [comment]
eu acho que as duas opções são interessantes; o `Imprimir` está presente no core do Plone (procurar em `portal_actions/document_actions/manage_main`); **Reportar erro** é algo que deveria ser incluso no core também… se não lembro mal o @tkimnguyen queria adicionar isso.

**Comment by hvelarde** [comment]
achei: https://github.com/plone/Products.CMFPlone/issues/1223

**Comment by tkimnguyen** [comment]
Yes, I still think there should be an obvious way to report a problem to the site owner, with contextual information, and that mechanism should be enabled & visible only if the site owner enables it in Site Setup somewhere.

**Comment by shogunbr** [comment]
Reportar erro também está presente nas notícias:
https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/browser/content/nitf_custom_view.py

Mas acho que isso poderia estar em todas as páginas, pegando algumas informações de contexto, como o navegador, SO, referer, automaticamente.

**Comment by idgserpro** [comment]
@hvelarde p/c. Não existe funcionalidade pronta do "relatar-erros", mas se você adicionar uma pasta de formulário com esse nome na raiz do site, o link é renderizado.

**Comment by hvelarde** [comment]
obrigado, essa tinha sido minha conclusão; estou substituindo a customização no template por um viewlet; isso tem que ser documentado no manual.
