### ISSUE TITLE
Tamanho da fonte pequena nos popups do editor TinyMCE 

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.temas#144]
Issue de referencia https://github.com/plonegovbr/brasil.gov.portal/issues/344 

As fontes dos popups estão muito pequenas do editor TinyMCE, o css do tema influenciou no tamanho.

**Comment by hvelarde** [comment]
precisa dessa issue aqui realmente?

**Comment by claytonc** [comment]
@hvelarde 
Pode ser fechar essa issue o pull request já foi efetuado.
