### ISSUE TITLE
Parte do CSS não renderiza

### ISSUE THREAD

**Issue by TZorawski** [plonegovbr/brasil.gov.temas#181]
Parte do CSS não está carregando. Esse problema surgiu há 1~2 meses.

Versão:
Portal Padrão 1.5
Plone 4.3.15 (4317)
CMF 2.2.10
Zope 2.13.26
Python 2.7.13 (default, Sep 8 2017, 07:19:26) [GCC 4.9.2]
PIL 3.3.0 (Pillow)
![portalplone](https://user-images.githubusercontent.com/26661643/39290139-fd3606ac-4904-11e8-9d3b-8440272586e7.png)

**Comment by hvelarde** [comment]
como comentou @almeidajeff isso aqui nẽo é um bug.
