### ISSUE TITLE
Problema do texto de destaque do topo no responsivo

### ISSUE THREAD

**Issue by agnogueira** [plonegovbr/brasil.gov.temas#250]
O tile de artigo, quando posicionado dentro de uma linha de destaque do topo aparece com problemas no texto, sobrepondo os elementos quando acessado no celular

![whatsapp image 2019-01-14 at 16 25 36](https://user-images.githubusercontent.com/1030139/51390503-9e440880-1b16-11e9-9929-28059e3ff409.jpeg)

**Comment by idgserpro** [comment]
@agnogueira Como podemos simular este problema?

**Comment by idgserpro** [comment]
@agnogueira conseguimos simular adicionando o estilo "linha de destaque topo" na linha que contém o tile de artigo.

**Comment by idgserpro** [comment]
corrigido por #251
