### ISSUE TITLE
Botões de rede social aparecem, sobrepondo o conteúdo da notícia

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.temas#261]
Botões sobrepõem notícia
===================

Visão de usuário editor, na aba conteúdo de uma notícia: - os botões de rede social aparecem, sobrepondo o conteúdo da notícia.

![noticia_visao_conteudo](https://user-images.githubusercontent.com/8203476/55722458-c425ce80-59dc-11e9-9e88-c2946bfa6869.jpg)

Botões sobrepõem opção de exclusão
============================

Além disso, em algumas situações, quando os botões estão "por cima" dos botões de ação do folder_contents, o botão excluir não funciona:

![Seleção_171](https://user-images.githubusercontent.com/8203476/58108544-6af7b000-7bc2-11e9-8854-9efe0b83aaf3.png)

**Comment by agnogueira** [comment]
@idgserpro acho que temos duas ações aqui.
A principal é não exibir os ícones na aba de conteúdo, é uma ação desnecessária aqui.
A outra seria centralizar essa tabela com o conteúdo, para manter o padrão visual do restante do site.
