### ISSUE TITLE
Compatibilidade entre versões do Plone

### ISSUE THREAD

**Issue by eduardoalcantara** [plonegovbr/brasil.gov.temas#268]
Quais as versões do Plone compatíveis com este pacote de temas? 3, 4, 5...

**Comment by idgserpro** [comment]
Todos os releases criados pelo IDG possuem suas pinagens definidas em https://github.com/plonegovbr/portalpadrao.release.

No caso, todas as versões lançadas do brasil.gov.temas são compatíveis com o Plone 4.3.x. Para ver a versão exata e demais dependências, favor ver o release desejado como por exemplo https://github.com/plonegovbr/portalpadrao.release/blob/master/2.1.1/versions.cfg.
