### ISSUE TITLE
Nova release?

### ISSUE THREAD

**Issue by wesleybl** [plonegovbr/brasil.gov.temas#277]
Pessoal, em função do período eleitoral, precisamos remover a marca do governo dos portais. Como não sabemos se a marca vai ser removida pela barra, criei a branch https://github.com/plonegovbr/brasil.gov.temas/tree/1.2.5-branch e removi a marca no tema. Alguém pode por favor criar uma nova release a partir dessa branch, ou me dar permissão no pypi pra que eu possa criar? Obrigado!

@ericof @hvelarde @rafaelbco @agnogueira @rodfersou

**Comment by ericof** [comment]
@wesleybl Eu vou te dar acesso no Pypi

**Comment by ericof** [comment]
@wesleybl Feito

**Comment by wesleybl** [comment]
Obrigado @ericof !

Gerei o release: https://pypi.org/project/brasil.gov.temas/1.2.5.1

**Comment by caduvieira** [comment]
creio que o logo de acesso a informação não teria problemas. você não está confundindo com o logo imbutido pela barra brasil não?

**Comment by wesleybl** [comment]
@caduvieira eu mantive o "Acesso a Informação":

https://github.com/plonegovbr/brasil.gov.temas/blob/1.2.5.1/src/brasil/gov/temas/themes/amarelo/index.html#L435

mas agora ele está no html e não é mais inserido pelo js da barra.

**Comment by wesleybl** [comment]
A imagem do Acesso a Informação, ainda é inserida pelo css barra. Mas a marcação html não.

**Comment by caduvieira** [comment]
> @caduvieira eu mantive o "Acesso a Informação":
> 
> https://github.com/plonegovbr/brasil.gov.temas/blob/1.2.5.1/src/brasil/gov/temas/themes/amarelo/index.html#L435
> 
> mas agora ele está no html e não é mais inserido pelo js da barra.

A ideia é que não precisaria de novo release para isso. Pois a barra Brasil seria a responsável por tirar/colocar os logos. Já teve uma discussão aqui https://github.com/plonegovbr/brasil.gov.temas/issues/109#issuecomment-102472212 sobre isso além de outras questões. O tema plone não seria responsável pelo logo pois quem seria responsável seria a barra brasil.

Mais aqui https://github.com/plonegovbr/brasil.gov.temas/pull/136 também

**Comment by wesleybl** [comment]
> Pois a barra Brasil seria a responsável por tirar/colocar os logos.

O problema é que não temos certeza se a barra vai ser atualizada.

**Comment by caduvieira** [comment]
A barra foi atualizada diretamente no ambiente (https://barra.brasil.gov.br) (https://barra.brasil.gov.br/exemplo_antiga.html) mas não publicaram no https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/tree/master 

Não sei quem foi o responsável pela atualização.

Caso não veja força a limpeza do cache do navegador.
