### ISSUE TITLE
Listagem – Regras de fontes

### ISSUE THREAD

**Issue by rennan** [plonegovbr/brasil.gov.temas#54]
1. Titulo da área: Open Sans, 28, Bold, #2C66CE, Caixa Alta
2. Chapéu: Open Sans, 11, regular, Cor da editoria
3. Tituto: Arial, 16, Bold, #172938, 21 de linha
4. Subtítulo da noticia: Arial, 14, regular, #172938, 21 de linha
5. Tags: Arial, 12, regular, #596E7F, 16 de linha
6. Bloco para mudar as noticias: 
   a) Anterior: Open Sans, 11, regular, #2C66CE
   b) Números das páginas – selecionada: Open Sans, 11, Bold, #36424D
   c) Caixa envolta dos números – não selecionado: tem uma moldura em volta 25x25 px, #C2C2C2
   d) Quando tiver mouse over, o número é sublinhado.

![portalbrasil_specs_listagem_regras](https://f.cloud.github.com/assets/1029822/1284468/49a60b1a-2f95-11e3-8533-1a85712b1375.jpg)

**Comment by rodfersou** [comment]
Vou fechar essa issue por se tratar da versão 1.x do projeto, caso alguém sinta necessidade, e queira trabalhar nisso, fique a vontade para reabrir.
