### ISSUE TITLE
Verificar a possibilidade de remover os prefixos CSS

### ISSUE THREAD

**Issue by rennan** [plonegovbr/brasil.gov.temas#73]
Eliminar no código CSS todos os prefixos declarados com propriedades de CSS3.
Ao invés disso, procurar utilizar uma biblioteca que faça isso para automatizar, como por exemplo a prefix-free. 

Artigo explicando o uso da biblioteca e o porquê de usá-la.
http://coding.smashingmagazine.com/2011/10/12/prefixfree-break-free-from-css-prefix-hell/

**Comment by rodfersou** [comment]
Na versão 2.x que estamos trabalhando isso acontece automaticamente pelo webpack através do plugin cssnext.

Caso alguém sinta a necessidade e queira trabalhar nessa issue para o tema 1.x, fique a vontade para reabrir a issue.
