### ISSUE TITLE
Reestruturar o sprite dos ícones

### ISSUE THREAD

**Issue by rennan** [plonegovbr/brasil.gov.temas#91]
Reestruturar o sprite da lista de ícones para todas as cores de tema e para o contraste.

Tema azul,
Tema branco,
Tema amarelo,
Tema verde,
Contraste

Nos tamanhos 20px e 40px.

**Comment by rodfersou** [comment]
Na nova versão do portal os sprites são processados por webpack.

Vou fechar esta issue, caso alguém sinta necessidade de rever os sprites na versão 1.x do tema fique a vontade para reabrir
